fluidPage(
  numericInput(inputId = "cutoff",
               "Percentage Survived",
               value=0.38,
               min=0.00,
               max=1.00,
               step=0.01),
  selectInput('Pclass','Cabin Class',
              choices=c('First Class'="1",
                        'Second Class'="2",
                        'Third Class'="3")),
  selectInput('Sex','Sex',
              choices=c('Male'="male",
                        'Female'="female")),
  numericInput('Age', 'Age (Average = 29.6)', value = 29.6, min = 0.1, max = 80.0, step=0.1),
  numericInput('SibSp', 'Number of siblings/spouses aboard (Average = 1)', value = 1, min = 0, max = 10, step=1),
  numericInput('Parch', 'Number of parents/children aboard  (Average = 0)', value = 0, min = 0, max = 10, step=1),
  numericInput('Fare (Average = 32.20)', 'Fare paid', value = 32.20, min = 0, max = 515, step=5),
  selectInput('Embarked','Embarkation Point',
              choices=c('Southampton'="S",
                        'Queenstown'="Q",
                        'Cherbourg'="C")),
  selectInput('Title','Title',
              choices=c('Mr'="Mr",
                        'Mrs'="Mrs",
                        'Miss'="Miss",
                        'Master'='Master',
                        'Titled (e.g.,"Rev","Dr",etc)','Titled')),
  numericInput('FamilySize', 'Number of family members (Average = 2)', value = 2, min = 0, max = 10, step=1),
  verbatimTextOutput('prob')
  
)